[workspace]
channels = ["conda-forge"]
name = "Gen-AI-BFA-Umbrella-repo"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[system-requirements]
cuda = "12.0"

[dependencies]
python = "3.12.*"
pytorch-gpu = "*"
torchvision = ">=0.25.0,<0.26"
safetensors = ">=0.7.0,<0.8"
huggingface_hub = ">=1.4.1,<2"
pillow = ">=12.1.0,<13"
numpy = ">=2.4.2,<3"
opencv = ">=4.13.0,<5"
tqdm = ">=4.67.3,<5"
einops = ">=0.8.2,<0.9"
matplotlib = ">=3.10.8,<4"

[pypi-dependencies]
onnxruntime-gpu = ">=1.24.1"
fashn-human-parser = ">=0.1.1"
fashn-vton = { path = "fashn-vton-1.5/", editable = true }
